# Generated by Django 3.1.7 on 2021-03-18 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст')),
                ('active', models.BooleanField(default=True, verbose_name='Активность')),
                ('template', models.CharField(default='page/index.html', max_length=500, verbose_name='Шаблон')),
                ('slug', models.SlugField(max_length=100, verbose_name='Url')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
    ]
