# Generated by Django 3.1.7 on 2021-03-15 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210315_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='mini_text',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Краткое содержание'),
        ),
    ]
